### ISSUE TITLE
Write up the first milestone for enabling other developers.

### ISSUE THREAD

**Issue by fuzzyweapon** [watch-the-skies/watch-the-skies#30]
# DoD

The first milestone should focus on removing critical barriers to getting other developers on board.  This should include any necessary support documentation as well as improvements in the dev environment setup and CI pipe needed.

It is important that the milestone documentation provide goals that inform or can be used to deduce  scoping.  The goals need to be flexible enough to withstand changing requirements.  They should not talk about implementation.
- [ ] Milestone Name
- [ ] Purpose/Value Statement
- [ ] Key Goals
### Not
- Feature list
## Steps
- [ ] Rough Goals
- [ ] Rough Purpose/Value Statement
- [ ] Rough Milestone Name
- [ ] Get feedback on rough draft.
- [ ] Address feedback.
- [ ] Label it with a prioritize label.
